"""0001 baseline: existing schema (workforce + BIM v1)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-06

Migratia de baseline care reflecta schema EXISTENTA inainte de adoptarea
Alembic. Pentru DB-uri existente (productie, dev) se ruleaza o singura data
'alembic stamp head' (NU 'upgrade head'), care doar inregistreaza ca DB-ul
e la zi cu acest baseline, fara sa modifice date.

Pentru DB-uri noi (CI, dezvoltare proaspata) 'alembic upgrade head' creeaza
schema completa de la zero, identic cu db.create_all() din models.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sarbatori_legale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('denumire', sa.String(length=200), nullable=False),
    sa.Column('an', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', name='uix_sarbatoare_data')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod')
    )
    op.create_table('tipuri_instalatii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=20), nullable=False),
    sa.Column('denumire', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('culoare_hex', sa.String(length=7), nullable=True),
    sa.Column('icon_css', sa.String(length=50), nullable=True),
    sa.Column('activ', sa.Boolean(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod')
    )
    op.create_table('angajati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nume', sa.String(length=100), nullable=False),
    sa.Column('prenume', sa.String(length=100), nullable=False),
    sa.Column('cnp', sa.String(length=13), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('adresa', sa.Text(), nullable=True),
    sa.Column('functie', sa.String(length=50), nullable=False),
    sa.Column('specializari', sa.Text(), nullable=True),
    sa.Column('data_nasterii', sa.Date(), nullable=True),
    sa.Column('data_angajare', sa.Date(), nullable=False),
    sa.Column('data_incetare', sa.Date(), nullable=True),
    sa.Column('tip_contract', sa.String(length=30), nullable=True),
    sa.Column('salariu_baza', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nr_contract', sa.String(length=50), nullable=True),
    sa.Column('serie_bi', sa.String(length=10), nullable=True),
    sa.Column('nr_bi', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('poza_profil', sa.String(length=255), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_actualizare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnp')
    )
    with op.batch_alter_table('angajati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_angajati_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('categorii_activitati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=200), nullable=False),
    sa.Column('tip_instalatie_id', sa.Integer(), nullable=True),
    sa.Column('unitate_masura_default', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tip_instalatie_id'], ['tipuri_instalatii.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipuri_documente_proiect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip_instalatie_id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('denumire', sa.String(length=300), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('obligatoriu', sa.Boolean(), nullable=True),
    sa.Column('exemple', sa.Text(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tip_instalatie_id'], ['tipuri_instalatii.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tip_instalatie_id', 'cod', name='uix_tip_doc_inst_cod')
    )
    op.create_table('utilizatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nume', sa.String(length=100), nullable=False),
    sa.Column('prenume', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('parola_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activ', sa.Boolean(), nullable=True),
    sa.Column('limba', sa.String(length=5), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('ultima_conectare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('utilizatori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilizatori_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('concedii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('data_start', sa.Date(), nullable=False),
    sa.Column('data_sfarsit', sa.Date(), nullable=False),
    sa.Column('nr_zile', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aprobat_de', sa.Integer(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['aprobat_de'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proiecte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('cod_proiect', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('locatie', sa.String(length=200), nullable=True),
    sa.Column('adresa_santier', sa.String(length=300), nullable=True),
    sa.Column('beneficiar', sa.String(length=200), nullable=True),
    sa.Column('nr_contract_beneficiar', sa.String(length=100), nullable=True),
    sa.Column('data_start', sa.Date(), nullable=False),
    sa.Column('data_sfarsit_planificat', sa.Date(), nullable=True),
    sa.Column('data_sfarsit_real', sa.Date(), nullable=True),
    sa.Column('buget_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buget_manopera', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_actualizare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_proiect')
    )
    with op.batch_alter_table('proiecte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proiecte_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rapoarte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip_raport', sa.String(length=50), nullable=False),
    sa.Column('titlu', sa.String(length=200), nullable=False),
    sa.Column('parametri', sa.Text(), nullable=True),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('data_generare', sa.DateTime(), nullable=True),
    sa.Column('generat_de', sa.Integer(), nullable=True),
    sa.Column('dimensiune_fisier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generat_de'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('angajat_proiect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('data_start', sa.Date(), nullable=False),
    sa.Column('data_sfarsit', sa.Date(), nullable=True),
    sa.Column('functie_pe_proiect', sa.String(length=100), nullable=True),
    sa.Column('tarif_negociat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('angajat_id', 'proiect_id', 'data_start', name='uix_angajat_proiect_data')
    )
    op.create_table('bim_santiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('adresa', sa.String(length=300), nullable=True),
    sa.Column('oras', sa.String(length=100), nullable=True),
    sa.Column('judet', sa.String(length=50), nullable=True),
    sa.Column('tara', sa.String(length=50), nullable=True),
    sa.Column('latitudine', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitudine', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cod', name='uix_santier_tenant_cod')
    )
    with op.batch_alter_table('bim_santiere', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_santiere_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_santiere_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_santiere_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uix_santier_source_extern', ['source_system', 'extern_id'], unique=False)

    op.create_table('documente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('tip', sa.String(length=50), nullable=False),
    sa.Column('nume_document', sa.String(length=255), nullable=False),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('marime_fisier', sa.Integer(), nullable=True),
    sa.Column('data_emitere', sa.Date(), nullable=True),
    sa.Column('data_expirare', sa.Date(), nullable=True),
    sa.Column('emitent', sa.String(length=200), nullable=True),
    sa.Column('serie_numar', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('incarcat_de', sa.Integer(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['incarcat_de'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documente_proiect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('tip_instalatie_id', sa.Integer(), nullable=False),
    sa.Column('tip_document_id', sa.Integer(), nullable=True),
    sa.Column('denumire_document', sa.String(length=500), nullable=False),
    sa.Column('nr_document', sa.String(length=100), nullable=True),
    sa.Column('revizie', sa.String(length=20), nullable=True),
    sa.Column('emitent', sa.String(length=200), nullable=True),
    sa.Column('elaborat_de', sa.String(length=200), nullable=True),
    sa.Column('data_emitere', sa.Date(), nullable=True),
    sa.Column('data_aprobare', sa.Date(), nullable=True),
    sa.Column('data_expirare', sa.Date(), nullable=True),
    sa.Column('versiune_curenta', sa.Boolean(), nullable=True),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('marime_fisier', sa.Integer(), nullable=True),
    sa.Column('tip_fisier', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aprobat_de_id', sa.Integer(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('etapa_proiect', sa.String(length=30), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('incarcat_de', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['incarcat_de'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tip_document_id'], ['tipuri_documente_proiect.id'], ),
    sa.ForeignKeyConstraint(['tip_instalatie_id'], ['tipuri_instalatii.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numar_inmatriculare', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('an_fabricatie', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('culoare', sa.String(length=30), nullable=True),
    sa.Column('tip_combustibil', sa.String(length=20), nullable=True),
    sa.Column('capacitate_cilindrica', sa.Integer(), nullable=True),
    sa.Column('putere_kw', sa.Integer(), nullable=True),
    sa.Column('tip_vehicul', sa.String(length=30), nullable=True),
    sa.Column('nr_locuri', sa.Integer(), nullable=True),
    sa.Column('masa_maxima', sa.Integer(), nullable=True),
    sa.Column('categorie_permis', sa.String(length=5), nullable=True),
    sa.Column('km_bord', sa.Integer(), nullable=True),
    sa.Column('consum_mediu', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('serie_civ', sa.String(length=20), nullable=True),
    sa.Column('nr_carte_identitate', sa.String(length=20), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('angajat_responsabil_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('poza', sa.String(length=255), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_achizitie', sa.Date(), nullable=True),
    sa.Column('data_prima_inmatriculare', sa.Date(), nullable=True),
    sa.Column('data_itp_expirare', sa.Date(), nullable=True),
    sa.Column('data_rca_expirare', sa.Date(), nullable=True),
    sa.Column('data_casco_expirare', sa.Date(), nullable=True),
    sa.Column('data_rovinieta_expirare', sa.Date(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_actualizare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_responsabil_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numar_inmatriculare'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('atribuiri_masini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masina_id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('data_atribuire', sa.Date(), nullable=False),
    sa.Column('data_returnare', sa.Date(), nullable=True),
    sa.Column('km_preluare', sa.Integer(), nullable=True),
    sa.Column('km_returnare', sa.Integer(), nullable=True),
    sa.Column('stare_preluare', sa.String(length=20), nullable=True),
    sa.Column('stare_returnare', sa.String(length=20), nullable=True),
    sa.Column('motiv', sa.Text(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('atribuit_de', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['atribuit_de'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['masina_id'], ['masini.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bim_cladiri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santier_id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('tip_constructie', sa.String(length=50), nullable=True),
    sa.Column('nr_niveluri', sa.Integer(), nullable=True),
    sa.Column('suprafata_totala', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['santier_id'], ['bim_santiere.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santier_id', 'cod', name='uix_cladire_santier_cod')
    )
    with op.batch_alter_table('bim_cladiri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_cladiri_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_cladiri_santier_id'), ['santier_id'], unique=False)

    op.create_table('conduceri_masini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masina_id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('km_start', sa.Integer(), nullable=False),
    sa.Column('km_sfarsit', sa.Integer(), nullable=True),
    sa.Column('ruta', sa.String(length=300), nullable=True),
    sa.Column('scop', sa.String(length=200), nullable=True),
    sa.Column('combustibil_alimentat', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cost_combustibil', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['masina_id'], ['masini.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defectiuni_masini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masina_id', sa.Integer(), nullable=False),
    sa.Column('raportat_de', sa.Integer(), nullable=True),
    sa.Column('data_raportare', sa.Date(), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=False),
    sa.Column('gravitate', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_rezolvare', sa.Date(), nullable=True),
    sa.Column('cost_reparatie', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_extern', sa.String(length=200), nullable=True),
    sa.Column('detalii_reparatie', sa.Text(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['masina_id'], ['masini.id'], ),
    sa.ForeignKeyConstraint(['raportat_de'], ['angajati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documente_masini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masina_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=50), nullable=False),
    sa.Column('nume_document', sa.String(length=200), nullable=True),
    sa.Column('numar_document', sa.String(length=100), nullable=True),
    sa.Column('emitent', sa.String(length=200), nullable=True),
    sa.Column('data_emitere', sa.Date(), nullable=True),
    sa.Column('data_expirare', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fisier', sa.String(length=255), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['masina_id'], ['masini.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revizii_documente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_proiect_id', sa.Integer(), nullable=False),
    sa.Column('nr_revizie', sa.Integer(), nullable=False),
    sa.Column('motiv_revizie', sa.Text(), nullable=True),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('data_revizie', sa.DateTime(), nullable=True),
    sa.Column('realizat_de', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_proiect_id'], ['documente_proiect.id'], ),
    sa.ForeignKeyConstraint(['realizat_de'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bim_modele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('santier_id', sa.Integer(), nullable=True),
    sa.Column('cladire_id', sa.Integer(), nullable=True),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('versiune', sa.String(length=50), nullable=True),
    sa.Column('autor', sa.String(length=150), nullable=True),
    sa.Column('data_emitere', sa.Date(), nullable=True),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('fisier_marime', sa.Integer(), nullable=True),
    sa.Column('extern_url', sa.String(length=500), nullable=True),
    sa.Column('nr_elemente', sa.Integer(), nullable=True),
    sa.Column('nr_spatii', sa.Integer(), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('procesare_status', sa.String(length=20), nullable=True),
    sa.Column('procesare_log', sa.Text(), nullable=True),
    sa.Column('incarcat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_incarcare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cladire_id'], ['bim_cladiri.id'], ),
    sa.ForeignKeyConstraint(['incarcat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['santier_id'], ['bim_santiere.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_modele', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_modele_cladire_id'), ['cladire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_modele_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_modele_santier_id'), ['santier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_modele_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bim_niveluri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cladire_id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=100), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('elevatie_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('inaltime_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cladire_id'], ['bim_cladiri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cladire_id', 'cod', name='uix_nivel_cladire_cod')
    )
    with op.batch_alter_table('bim_niveluri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_niveluri_cladire_id'), ['cladire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_niveluri_extern_id'), ['extern_id'], unique=False)

    op.create_table('bim_external_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=30), nullable=False),
    sa.Column('extern_id', sa.String(length=200), nullable=False),
    sa.Column('model_bim_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_bim_id'], ['bim_modele.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'source_system', 'extern_id', name='uix_extmap_unique')
    )
    with op.batch_alter_table('bim_external_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_external_mappings_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_external_mappings_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_external_mappings_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_external_mappings_model_bim_id'), ['model_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_external_mappings_source_system'), ['source_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_external_mappings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_extmap_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_extmap_lookup', ['source_system', 'extern_id'], unique=False)

    op.create_table('bim_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cladire_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('tip_zona', sa.String(length=50), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cladire_id'], ['bim_cladiri.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['bim_niveluri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cladire_id', 'cod', name='uix_zona_cladire_cod')
    )
    with op.batch_alter_table('bim_zone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_zone_cladire_id'), ['cladire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_zone_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_zone_nivel_id'), ['nivel_id'], unique=False)

    op.create_table('bim_spatii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('tip_spatiu', sa.String(length=50), nullable=True),
    sa.Column('suprafata_mp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inaltime_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volum_mc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nivel_id'], ['bim_niveluri.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['bim_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel_id', 'cod', name='uix_spatiu_nivel_cod')
    )
    with op.batch_alter_table('bim_spatii', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_spatii_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_spatii_nivel_id'), ['nivel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_spatii_zona_id'), ['zona_id'], unique=False)

    op.create_table('bim_elemente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spatiu_id', sa.Integer(), nullable=True),
    sa.Column('nivel_id', sa.Integer(), nullable=True),
    sa.Column('cladire_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=100), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=True),
    sa.Column('tip_element', sa.String(length=50), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('cantitate', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unitate_masura', sa.String(length=20), nullable=True),
    sa.Column('ifc_global_id', sa.String(length=100), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('model_bim_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('proprietati_json', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_actualizare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cladire_id'], ['bim_cladiri.id'], ),
    sa.ForeignKeyConstraint(['model_bim_id'], ['bim_modele.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['bim_niveluri.id'], ),
    sa.ForeignKeyConstraint(['spatiu_id'], ['bim_spatii.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_elemente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_elemente_cladire_id'), ['cladire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elemente_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elemente_ifc_global_id'), ['ifc_global_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elemente_model_bim_id'), ['model_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elemente_nivel_id'), ['nivel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elemente_spatiu_id'), ['spatiu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elemente_tip_element'), ['tip_element'], unique=False)

    op.create_table('bim_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_bim_id', sa.Integer(), nullable=False),
    sa.Column('producator', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('serial', sa.String(length=150), nullable=True),
    sa.Column('cod_intern', sa.String(length=100), nullable=True),
    sa.Column('data_punere_functiune', sa.Date(), nullable=True),
    sa.Column('data_garantie_pana', sa.Date(), nullable=True),
    sa.Column('interval_mentenanta_zile', sa.Integer(), nullable=True),
    sa.Column('ultima_mentenanta', sa.Date(), nullable=True),
    sa.Column('urmatoarea_mentenanta', sa.Date(), nullable=True),
    sa.Column('cost_achizitie', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('fisa_tehnica_path', sa.String(length=500), nullable=True),
    sa.Column('manual_path', sa.String(length=500), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_assets_element_bim_id'), ['element_bim_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bim_assets_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_assets_serial'), ['serial'], unique=False)

    op.create_table('bim_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('element_bim_id', sa.Integer(), nullable=True),
    sa.Column('spatiu_id', sa.Integer(), nullable=True),
    sa.Column('nivel_id', sa.Integer(), nullable=True),
    sa.Column('cladire_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=50), nullable=True),
    sa.Column('titlu', sa.String(length=300), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('tip', sa.String(length=50), nullable=True),
    sa.Column('severitate', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('raportat_de_id', sa.Integer(), nullable=True),
    sa.Column('asignat_id', sa.Integer(), nullable=True),
    sa.Column('data_raportare', sa.Date(), nullable=True),
    sa.Column('data_termen', sa.Date(), nullable=True),
    sa.Column('data_rezolvare', sa.Date(), nullable=True),
    sa.Column('bcf_topic_guid', sa.String(length=100), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_actualizare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignat_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['cladire_id'], ['bim_cladiri.id'], ),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['bim_niveluri.id'], ),
    sa.ForeignKeyConstraint(['raportat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['spatiu_id'], ['bim_spatii.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_issues_bcf_topic_guid'), ['bcf_topic_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_issues_cladire_id'), ['cladire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_issues_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_issues_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_issues_nivel_id'), ['nivel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_issues_spatiu_id'), ['spatiu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_issues_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pontaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('element_bim_id', sa.Integer(), nullable=True),
    sa.Column('spatiu_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora_start', sa.String(length=5), nullable=True),
    sa.Column('ora_sfarsit', sa.String(length=5), nullable=True),
    sa.Column('ore_lucrate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ore_normale', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ore_suplimentare_50', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ore_suplimentare_100', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tip_zi', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aprobat_de', sa.Integer(), nullable=True),
    sa.Column('data_aprobare', sa.DateTime(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('motiv_respingere', sa.Text(), nullable=True),
    sa.Column('introdus_de', sa.Integer(), nullable=True),
    sa.Column('data_introducere', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['aprobat_de'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['introdus_de'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['spatiu_id'], ['bim_spatii.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('angajat_id', 'data', name='uix_pontaj_angajat_data')
    )
    with op.batch_alter_table('pontaje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pontaje_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pontaje_spatiu_id'), ['spatiu_id'], unique=False)

    op.create_table('rapoarte_activitati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angajat_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('element_bim_id', sa.Integer(), nullable=True),
    sa.Column('spatiu_id', sa.Integer(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tip_instalatie_id', sa.Integer(), nullable=True),
    sa.Column('categorie_activitate_id', sa.Integer(), nullable=True),
    sa.Column('zona_lucru', sa.String(length=200), nullable=True),
    sa.Column('activitate_principala', sa.String(length=500), nullable=False),
    sa.Column('activitate_detaliata', sa.Text(), nullable=True),
    sa.Column('tip_activitate', sa.String(length=20), nullable=False),
    sa.Column('data_sfarsit', sa.Date(), nullable=True),
    sa.Column('numar_saptamana', sa.Integer(), nullable=True),
    sa.Column('luna_an', sa.String(length=7), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('subordonati_ids', sa.Text(), nullable=True),
    sa.Column('proiecte_ids', sa.Text(), nullable=True),
    sa.Column('include_sambata', sa.Boolean(), nullable=False),
    sa.Column('include_duminica', sa.Boolean(), nullable=False),
    sa.Column('detalii_pe_zi', sa.Text(), nullable=True),
    sa.Column('ore_lucrate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status_executie', sa.String(length=20), nullable=False),
    sa.Column('materiale_folosite', sa.Text(), nullable=True),
    sa.Column('echipamente_folosite', sa.Text(), nullable=True),
    sa.Column('cantitate_executata', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unitate_masura', sa.String(length=20), nullable=True),
    sa.Column('procent_realizare', sa.Integer(), nullable=True),
    sa.Column('probleme_intampinate', sa.Text(), nullable=True),
    sa.Column('solutii_aplicate', sa.Text(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('necesita_aprobare_tehnica', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aprobat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_aprobare', sa.DateTime(), nullable=True),
    sa.Column('motiv_respingere', sa.Text(), nullable=True),
    sa.Column('introdus_la', sa.DateTime(), nullable=True),
    sa.Column('modificat_la', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angajat_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['aprobat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['categorie_activitate_id'], ['categorii_activitati.id'], ),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['spatiu_id'], ['bim_spatii.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['angajati.id'], ),
    sa.ForeignKeyConstraint(['tip_instalatie_id'], ['tipuri_instalatii.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['bim_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rapoarte_activitati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rapoarte_activitati_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rapoarte_activitati_spatiu_id'), ['spatiu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rapoarte_activitati_zona_id'), ['zona_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapoarte_activitati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rapoarte_activitati_zona_id'))
        batch_op.drop_index(batch_op.f('ix_rapoarte_activitati_spatiu_id'))
        batch_op.drop_index(batch_op.f('ix_rapoarte_activitati_element_bim_id'))

    op.drop_table('rapoarte_activitati')
    with op.batch_alter_table('pontaje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pontaje_spatiu_id'))
        batch_op.drop_index(batch_op.f('ix_pontaje_element_bim_id'))

    op.drop_table('pontaje')
    with op.batch_alter_table('bim_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_issues_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_issues_spatiu_id'))
        batch_op.drop_index(batch_op.f('ix_bim_issues_nivel_id'))
        batch_op.drop_index(batch_op.f('ix_bim_issues_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_issues_element_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_issues_cladire_id'))
        batch_op.drop_index(batch_op.f('ix_bim_issues_bcf_topic_guid'))

    op.drop_table('bim_issues')
    with op.batch_alter_table('bim_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_assets_serial'))
        batch_op.drop_index(batch_op.f('ix_bim_assets_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_assets_element_bim_id'))

    op.drop_table('bim_assets')
    with op.batch_alter_table('bim_elemente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_elemente_tip_element'))
        batch_op.drop_index(batch_op.f('ix_bim_elemente_spatiu_id'))
        batch_op.drop_index(batch_op.f('ix_bim_elemente_nivel_id'))
        batch_op.drop_index(batch_op.f('ix_bim_elemente_model_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_elemente_ifc_global_id'))
        batch_op.drop_index(batch_op.f('ix_bim_elemente_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_elemente_cladire_id'))

    op.drop_table('bim_elemente')
    with op.batch_alter_table('bim_spatii', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_spatii_zona_id'))
        batch_op.drop_index(batch_op.f('ix_bim_spatii_nivel_id'))
        batch_op.drop_index(batch_op.f('ix_bim_spatii_extern_id'))

    op.drop_table('bim_spatii')
    with op.batch_alter_table('bim_zone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_zone_nivel_id'))
        batch_op.drop_index(batch_op.f('ix_bim_zone_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_zone_cladire_id'))

    op.drop_table('bim_zone')
    with op.batch_alter_table('bim_external_mappings', schema=None) as batch_op:
        batch_op.drop_index('ix_extmap_lookup')
        batch_op.drop_index('ix_extmap_entity')
        batch_op.drop_index(batch_op.f('ix_bim_external_mappings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_external_mappings_source_system'))
        batch_op.drop_index(batch_op.f('ix_bim_external_mappings_model_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_external_mappings_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_external_mappings_entity_type'))
        batch_op.drop_index(batch_op.f('ix_bim_external_mappings_entity_id'))

    op.drop_table('bim_external_mappings')
    with op.batch_alter_table('bim_niveluri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_niveluri_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_niveluri_cladire_id'))

    op.drop_table('bim_niveluri')
    with op.batch_alter_table('bim_modele', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_modele_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_modele_santier_id'))
        batch_op.drop_index(batch_op.f('ix_bim_modele_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_modele_cladire_id'))

    op.drop_table('bim_modele')
    op.drop_table('revizii_documente')
    op.drop_table('documente_masini')
    op.drop_table('defectiuni_masini')
    op.drop_table('conduceri_masini')
    with op.batch_alter_table('bim_cladiri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_cladiri_santier_id'))
        batch_op.drop_index(batch_op.f('ix_bim_cladiri_extern_id'))

    op.drop_table('bim_cladiri')
    op.drop_table('atribuiri_masini')
    op.drop_table('masini')
    op.drop_table('documente_proiect')
    op.drop_table('documente')
    with op.batch_alter_table('bim_santiere', schema=None) as batch_op:
        batch_op.drop_index('uix_santier_source_extern')
        batch_op.drop_index(batch_op.f('ix_bim_santiere_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_santiere_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_bim_santiere_extern_id'))

    op.drop_table('bim_santiere')
    op.drop_table('angajat_proiect')
    op.drop_table('rapoarte')
    with op.batch_alter_table('proiecte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proiecte_tenant_id'))

    op.drop_table('proiecte')
    op.drop_table('concedii')
    with op.batch_alter_table('utilizatori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilizatori_tenant_id'))

    op.drop_table('utilizatori')
    op.drop_table('tipuri_documente_proiect')
    op.drop_table('categorii_activitati')
    with op.batch_alter_table('angajati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_angajati_tenant_id'))

    op.drop_table('angajati')
    op.drop_table('tipuri_instalatii')
    op.drop_table('tenants')
    op.drop_table('sarbatori_legale')
    # ### end Alembic commands ###
