"""0003 BIM model versions + CDE workflow (Faza 3)

Revision ID: 0003_versioning
Revises: 0002_audit_flags
Create Date: 2026-05-10

Adauga tabelul bim_model_versions: 1 ModelBIM -> N versiuni cu workflow CDE
(wip -> shared -> published -> archived/rejected, conform ISO 19650).

Strict aditiv: nu modifica tabelul bim_modele existent. Modelele fara
versiuni explicite continua sa functioneze ca pana acum.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_versioning'
down_revision: Union[str, Sequence[str], None] = '0002_audit_flags'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('versiune', sa.String(length=50), nullable=False),
    sa.Column('disciplina', sa.String(length=20), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('fisier_marime', sa.Integer(), nullable=True),
    sa.Column('fisier_hash', sa.String(length=64), nullable=True),
    sa.Column('extern_url', sa.String(length=500), nullable=True),
    sa.Column('extern_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=30), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('data_share', sa.DateTime(), nullable=True),
    sa.Column('data_publicare', sa.DateTime(), nullable=True),
    sa.Column('data_respingere', sa.DateTime(), nullable=True),
    sa.Column('data_arhivare', sa.DateTime(), nullable=True),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.Column('aprobat_de_id', sa.Integer(), nullable=True),
    sa.Column('comentariu_aprobare', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprobat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['bim_modele.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'versiune', name='uix_model_version_label')
    )
    with op.batch_alter_table('bim_model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_model_versions_aprobat_de_id'), ['aprobat_de_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_model_versions_creat_de_id'), ['creat_de_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_model_versions_disciplina'), ['disciplina'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_model_versions_extern_id'), ['extern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_model_versions_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_model_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_model_versions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_model_version_status', ['model_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_model_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_model_version_status')
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_status'))
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_model_id'))
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_extern_id'))
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_disciplina'))
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_creat_de_id'))
        batch_op.drop_index(batch_op.f('ix_bim_model_versions_aprobat_de_id'))

    op.drop_table('bim_model_versions')
    # ### end Alembic commands ###
