"""0004 rules + clash detection (Faza 4)

Revision ID: 0004_rules_clash
Revises: 0003_versioning
Create Date: 2026-05-10

Adauga 4 tabele pentru rule engine + clash detection:
- bim_rules: definitii reguli declarative (DSL JSON)
- bim_rule_violations: violari detectate la rulare
- bim_clash_runs: sesiuni de detectie clash
- bim_clash_results: clash-uri concrete intre 2 elemente

Strict aditiv: nu modifica nicio tabela existenta.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_rules_clash'
down_revision: Union[str, Sequence[str], None] = '0003_versioning'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=30), nullable=False),
    sa.Column('severitate', sa.String(length=20), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('definitie_json', sa.Text(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_modificare', sa.DateTime(), nullable=True),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cod', name='uix_rule_tenant_cod')
    )
    with op.batch_alter_table('bim_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_rules_activa'), ['activa'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rules_categorie'), ['categorie'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rules_cod'), ['cod'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bim_clash_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('santier_id', sa.Integer(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('nr_clash_uri', sa.Integer(), nullable=True),
    sa.Column('nr_critica', sa.Integer(), nullable=True),
    sa.Column('nr_mare', sa.Integer(), nullable=True),
    sa.Column('nr_medie', sa.Integer(), nullable=True),
    sa.Column('nr_mica', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('durata_ms', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('data_rulare', sa.DateTime(), nullable=False),
    sa.Column('rulat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['bim_modele.id'], ),
    sa.ForeignKeyConstraint(['rulat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['santier_id'], ['bim_santiere.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_clash_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_clash_runs_data_rulare'), ['data_rulare'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_runs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_runs_santier_id'), ['santier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bim_clash_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('element_a_id', sa.Integer(), nullable=False),
    sa.Column('element_b_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('severitate', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mesaj', sa.String(length=500), nullable=False),
    sa.Column('detalii_json', sa.Text(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('data_detectie', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_a_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['element_b_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['bim_issues.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['bim_clash_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_clash_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_clash_results_element_a_id'), ['element_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_results_element_b_id'), ['element_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_results_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_results_severitate'), ['severitate'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_results_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_results_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_clash_results_tip'), ['tip'], unique=False)
        batch_op.create_index('ix_clash_run_severity', ['run_id', 'severitate'], unique=False)
        batch_op.create_index('ix_clash_status', ['status'], unique=False)

    op.create_table('bim_rule_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('element_bim_id', sa.Integer(), nullable=True),
    sa.Column('spatiu_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mesaj', sa.String(length=500), nullable=False),
    sa.Column('detalii_json', sa.Text(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('data_detectie', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['bim_issues.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['bim_rules.id'], ),
    sa.ForeignKeyConstraint(['spatiu_id'], ['bim_spatii.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_rule_violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_data_detectie'), ['data_detectie'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_spatiu_id'), ['spatiu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_rule_violations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_violation_rule_status', ['rule_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_rule_violations', schema=None) as batch_op:
        batch_op.drop_index('ix_violation_rule_status')
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_status'))
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_spatiu_id'))
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_run_id'))
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_rule_id'))
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_element_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_rule_violations_data_detectie'))

    op.drop_table('bim_rule_violations')
    with op.batch_alter_table('bim_clash_results', schema=None) as batch_op:
        batch_op.drop_index('ix_clash_status')
        batch_op.drop_index('ix_clash_run_severity')
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_tip'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_status'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_severitate'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_element_b_id'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_results_element_a_id'))

    op.drop_table('bim_clash_results')
    with op.batch_alter_table('bim_clash_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_clash_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_runs_santier_id'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_runs_model_id'))
        batch_op.drop_index(batch_op.f('ix_bim_clash_runs_data_rulare'))

    op.drop_table('bim_clash_runs')
    with op.batch_alter_table('bim_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_rules_cod'))
        batch_op.drop_index(batch_op.f('ix_bim_rules_categorie'))
        batch_op.drop_index(batch_op.f('ix_bim_rules_activa'))

    op.drop_table('bim_rules')
    # ### end Alembic commands ###
