"""0005 4D Schedule + 5D Cost (Faza 5)

Revision ID: 0005_4d_5d
Revises: 0004_rules_clash
Create Date: 2026-05-10

Adauga 2 tabele noi:
- bim_task_schedules: link element <-> task cu interval planificat (4D)
- bim_cost_items: cost per element (cantitate * pret_unitar) cu categorii (5D)

Strict aditiv. Nu modifica nicio tabela existenta.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_4d_5d'
down_revision: Union[str, Sequence[str], None] = '0004_rules_clash'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_cost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('element_bim_id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=30), nullable=False),
    sa.Column('faza', sa.String(length=50), nullable=True),
    sa.Column('descriere', sa.String(length=300), nullable=False),
    sa.Column('unitate', sa.String(length=20), nullable=False),
    sa.Column('cantitate', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('pret_unitar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valuta', sa.String(length=3), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('referinta_extern', sa.String(length=100), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_modificare', sa.DateTime(), nullable=True),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_cost_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_cost_items_categorie'), ['categorie'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_cost_items_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_cost_items_faza'), ['faza'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_cost_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_cost_items_tip'), ['tip'], unique=False)
        batch_op.create_index('ix_cost_element_categorie', ['element_bim_id', 'categorie'], unique=False)

    op.create_table('bim_task_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('element_bim_id', sa.Integer(), nullable=False),
    sa.Column('faza', sa.String(length=50), nullable=False),
    sa.Column('disciplina', sa.String(length=20), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('data_start_plan', sa.Date(), nullable=False),
    sa.Column('data_sfarsit_plan', sa.Date(), nullable=False),
    sa.Column('data_start_real', sa.Date(), nullable=True),
    sa.Column('data_sfarsit_real', sa.Date(), nullable=True),
    sa.Column('progres_pct', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raport_activitate_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=True),
    sa.Column('data_modificare', sa.DateTime(), nullable=True),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['raport_activitate_id'], ['rapoarte_activitati.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_task_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_data_sfarsit_plan'), ['data_sfarsit_plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_data_start_plan'), ['data_start_plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_disciplina'), ['disciplina'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_raport_activitate_id'), ['raport_activitate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_task_schedules_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_schedule_dates', ['data_start_plan', 'data_sfarsit_plan'], unique=False)
        batch_op.create_index('ix_schedule_element_faza', ['element_bim_id', 'faza'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_task_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_element_faza')
        batch_op.drop_index('ix_schedule_dates')
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_raport_activitate_id'))
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_element_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_disciplina'))
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_data_start_plan'))
        batch_op.drop_index(batch_op.f('ix_bim_task_schedules_data_sfarsit_plan'))

    op.drop_table('bim_task_schedules')
    with op.batch_alter_table('bim_cost_items', schema=None) as batch_op:
        batch_op.drop_index('ix_cost_element_categorie')
        batch_op.drop_index(batch_op.f('ix_bim_cost_items_tip'))
        batch_op.drop_index(batch_op.f('ix_bim_cost_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_cost_items_faza'))
        batch_op.drop_index(batch_op.f('ix_bim_cost_items_element_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_cost_items_categorie'))

    op.drop_table('bim_cost_items')
    # ### end Alembic commands ###
