"""0006 IoT Sensors + Time-series + Alerts (Faza 6 Digital Twin)

Revision ID: 0006_iot
Revises: 0005_4d_5d
Create Date: 2026-05-10

Adauga 3 tabele noi:
- bim_senzori: definitia senzorilor (token-auth pentru ingest)
- bim_sensor_readings: time-series append-only (index pe (senzor_id, ts))
- bim_sensor_alerts: alerte generate la threshold violation

Strict aditiv. Nu modifica nicio tabela existenta.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_iot'
down_revision: Union[str, Sequence[str], None] = '0005_4d_5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_senzori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('element_bim_id', sa.Integer(), nullable=True),
    sa.Column('spatiu_id', sa.Integer(), nullable=True),
    sa.Column('cladire_id', sa.Integer(), nullable=True),
    sa.Column('cod', sa.String(length=80), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('unitate', sa.String(length=20), nullable=False),
    sa.Column('threshold_min', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('threshold_max', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('producator', sa.String(length=100), nullable=True),
    sa.Column('model_hardware', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('ultima_valoare', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('ultima_citire_at', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('data_modificare', sa.DateTime(), nullable=True),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cladire_id'], ['bim_cladiri.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['element_bim_id'], ['bim_elemente.id'], ),
    sa.ForeignKeyConstraint(['spatiu_id'], ['bim_spatii.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cod', name='uix_senzor_tenant_cod')
    )
    with op.batch_alter_table('bim_senzori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_senzori_activ'), ['activ'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_bim_senzori_cladire_id'), ['cladire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_cod'), ['cod'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_element_bim_id'), ['element_bim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_spatiu_id'), ['spatiu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_tip'), ['tip'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_senzori_ultima_citire_at'), ['ultima_citire_at'], unique=False)
        batch_op.create_index('ix_senzor_tip_activ', ['tip', 'activ'], unique=False)

    op.create_table('bim_sensor_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('senzor_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('severitate', sa.String(length=20), nullable=False),
    sa.Column('valoare', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('threshold_violat', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('mesaj', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('data_alerta', sa.DateTime(), nullable=False),
    sa.Column('data_confirmare', sa.DateTime(), nullable=True),
    sa.Column('data_rezolvare', sa.DateTime(), nullable=True),
    sa.Column('confirmat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['bim_issues.id'], ),
    sa.ForeignKeyConstraint(['senzor_id'], ['bim_senzori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_sensor_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_senzor_status', ['senzor_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_alerts_data_alerta'), ['data_alerta'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_alerts_senzor_id'), ['senzor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_alerts_severitate'), ['severitate'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_alerts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bim_sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('senzor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('valoare', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('calitate', sa.String(length=20), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['senzor_id'], ['bim_senzori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_sensor_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_sensor_readings_senzor_id'), ['senzor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_readings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_sensor_readings_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_reading_senzor_ts', ['senzor_id', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_senzor_ts')
        batch_op.drop_index(batch_op.f('ix_bim_sensor_readings_ts'))
        batch_op.drop_index(batch_op.f('ix_bim_sensor_readings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_sensor_readings_senzor_id'))

    op.drop_table('bim_sensor_readings')
    with op.batch_alter_table('bim_sensor_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_sensor_alerts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_sensor_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_bim_sensor_alerts_severitate'))
        batch_op.drop_index(batch_op.f('ix_bim_sensor_alerts_senzor_id'))
        batch_op.drop_index(batch_op.f('ix_bim_sensor_alerts_data_alerta'))
        batch_op.drop_index('ix_alert_senzor_status')

    op.drop_table('bim_sensor_alerts')
    with op.batch_alter_table('bim_senzori', schema=None) as batch_op:
        batch_op.drop_index('ix_senzor_tip_activ')
        batch_op.drop_index(batch_op.f('ix_bim_senzori_ultima_citire_at'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_tip'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_spatiu_id'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_element_bim_id'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_cod'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_cladire_id'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_api_key'))
        batch_op.drop_index(batch_op.f('ix_bim_senzori_activ'))

    op.drop_table('bim_senzori')
    # ### end Alembic commands ###
