"""0007 Real-time collab + Kanban (Faza 7)

Revision ID: 0007_realtime
Revises: 0006_iot
Create Date: 2026-05-11

Adauga 3 tabele noi:
- bim_comments: comentarii pe IssueBIM (cu sub-threads)
- bim_user_presence: heartbeat per user (1 row/user)
- bim_realtime_events: event stream pentru SSE consumers

Strict aditiv. Nu modifica nicio tabela existenta.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007_realtime'
down_revision: Union[str, Sequence[str], None] = '0006_iot'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_user_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=30), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('user_nume', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_user_presence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_user_presence_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_user_presence_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_user_presence_user_id'), ['user_id'], unique=True)

    op.create_table('bim_realtime_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('santier_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['santier_id'], ['bim_santiere.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_realtime_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_realtime_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_realtime_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_realtime_events_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_realtime_events_santier_id'), ['santier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_realtime_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_realtime_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_event_created', ['created_at'], unique=False)
        batch_op.create_index('ix_event_scope', ['proiect_id', 'santier_id', 'id'], unique=False)

    op.create_table('bim_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('mentions', sa.String(length=500), nullable=True),
    sa.Column('sters', sa.Boolean(), nullable=False),
    sa.Column('sters_la', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('data_editare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['bim_issues.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['bim_comments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_comments_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_comments_data_creare'), ['data_creare'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_comments_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_comments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_comment_issue_data', ['issue_id', 'data_creare'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_issue_data')
        batch_op.drop_index(batch_op.f('ix_bim_comments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_bim_comments_issue_id'))
        batch_op.drop_index(batch_op.f('ix_bim_comments_data_creare'))
        batch_op.drop_index(batch_op.f('ix_bim_comments_autor_id'))

    op.drop_table('bim_comments')
    with op.batch_alter_table('bim_realtime_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_scope')
        batch_op.drop_index('ix_event_created')
        batch_op.drop_index(batch_op.f('ix_bim_realtime_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_bim_realtime_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_realtime_events_santier_id'))
        batch_op.drop_index(batch_op.f('ix_bim_realtime_events_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_bim_realtime_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_bim_realtime_events_created_at'))

    op.drop_table('bim_realtime_events')
    with op.batch_alter_table('bim_user_presence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_user_presence_user_id'))
        batch_op.drop_index(batch_op.f('ix_bim_user_presence_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_user_presence_last_seen_at'))

    op.drop_table('bim_user_presence')
    # ### end Alembic commands ###
