"""0008 Governance (RBAC fin + API tokens) - Faza 8 final

Revision ID: 0008_governance
Revises: 0007_realtime
Create Date: 2026-05-11

Adauga 2 tabele noi pentru guvernanta:
- bim_role_assignments: roluri fine pe scope (santier/cladire/disciplina)
- bim_api_tokens: tokens publici cu scopes pentru integrari externe

Strict aditiv. Nu modifica nicio tabela existenta.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008_governance'
down_revision: Union[str, Sequence[str], None] = '0007_realtime'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('nume', sa.String(length=150), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_api_tokens_activ'), ['activ'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_api_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_api_tokens_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_api_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_api_tokens_token'), ['token'], unique=True)

    op.create_table('bim_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('scope_disciplina', sa.String(length=20), nullable=True),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.Column('data_start', sa.Date(), nullable=True),
    sa.Column('data_sfarsit', sa.Date(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_role_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_activ'), ['activ'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_scope_disciplina'), ['scope_disciplina'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_role_assignments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_rba_user_rol_scope', ['user_id', 'rol', 'scope_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_role_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_rba_user_rol_scope')
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_scope_type'))
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_scope_id'))
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_scope_disciplina'))
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_rol'))
        batch_op.drop_index(batch_op.f('ix_bim_role_assignments_activ'))

    op.drop_table('bim_role_assignments')
    with op.batch_alter_table('bim_api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_api_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_bim_api_tokens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bim_api_tokens_owner_id'))
        batch_op.drop_index(batch_op.f('ix_bim_api_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_bim_api_tokens_activ'))

    op.drop_table('bim_api_tokens')
    # ### end Alembic commands ###
