"""0009 contract controls

Revision ID: 0009_contract_controls
Revises: 0008_governance
Create Date: 2026-05-17 11:46:01.196479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009_contract_controls'
down_revision: Union[str, Sequence[str], None] = '0008_governance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('entitate_tinta', sa.String(length=30), nullable=False),
    sa.Column('id_entitate_tinta', sa.Integer(), nullable=False),
    sa.Column('tip_fisier', sa.String(length=20), nullable=False),
    sa.Column('fisier_path', sa.String(length=500), nullable=False),
    sa.Column('nume_original', sa.String(length=255), nullable=True),
    sa.Column('dimensiune_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('incarcat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_incarcare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incarcat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexe', schema=None) as batch_op:
        batch_op.create_index('ix_anexa_tinta', ['entitate_tinta', 'id_entitate_tinta'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexe_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexe_tip_fisier'), ['tip_fisier'], unique=False)

    op.create_table('notificari_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('utilizator_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=40), nullable=False),
    sa.Column('titlu', sa.String(length=255), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('entitate_referinta', sa.String(length=30), nullable=True),
    sa.Column('id_entitate_referinta', sa.Integer(), nullable=True),
    sa.Column('citita', sa.Boolean(), nullable=False),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('data_citire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utilizator_id'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificari_app', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_citita_data', ['utilizator_id', 'citita', 'data_creare'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificari_app_citita'), ['citita'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificari_app_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificari_app_tip'), ['tip'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificari_app_utilizator_id'), ['utilizator_id'], unique=False)

    op.create_table('contracte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('parinte_contract_id', sa.Integer(), nullable=True),
    sa.Column('nr_contract', sa.String(length=100), nullable=False),
    sa.Column('data_semnare', sa.Date(), nullable=False),
    sa.Column('data_inceput_referinta', sa.Date(), nullable=True),
    sa.Column('data_inceput_executie', sa.Date(), nullable=True),
    sa.Column('data_finalizare_planificata', sa.Date(), nullable=True),
    sa.Column('valoare_totala', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('beneficiar', sa.String(length=255), nullable=True),
    sa.Column('antreprenor', sa.String(length=255), nullable=True),
    sa.Column('obiect_contract', sa.Text(), nullable=True),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['parinte_contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nr_contract', name='uix_contract_nr_per_tenant')
    )
    with op.batch_alter_table('contracte', schema=None) as batch_op:
        batch_op.create_index('ix_contract_finalizare', ['data_finalizare_planificata'], unique=False)
        batch_op.create_index('ix_contract_proiect_status', ['proiect_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracte_parinte_contract_id'), ['parinte_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracte_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracte_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracte_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rapoarte_lucrari_proiect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('luna', sa.Integer(), nullable=False),
    sa.Column('an', sa.Integer(), nullable=False),
    sa.Column('data_intocmire', sa.Date(), nullable=False),
    sa.Column('ore_totale_manopera', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('progres_descriere', sa.Text(), nullable=True),
    sa.Column('task_program_acoperite_json', sa.Text(), nullable=False),
    sa.Column('intocmit_de_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intocmit_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rapoarte_lucrari_proiect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rapoarte_lucrari_proiect_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rapoarte_lucrari_proiect_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_raport_lucr_proiect_anluna', ['proiect_id', 'an', 'luna'], unique=False)

    op.create_table('reguli_notificare_proiect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('tip_eveniment', sa.String(length=40), nullable=False),
    sa.Column('email_destinatari_json', sa.Text(), nullable=False),
    sa.Column('zile_anticipare', sa.Integer(), nullable=False),
    sa.Column('email_activ', sa.Boolean(), nullable=False),
    sa.Column('in_app_activ', sa.Boolean(), nullable=False),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proiect_id', 'tip_eveniment', name='uix_regula_proiect_eveniment')
    )
    with op.batch_alter_table('reguli_notificare_proiect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reguli_notificare_proiect_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reguli_notificare_proiect_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reguli_notificare_proiect_tip_eveniment'), ['tip_eveniment'], unique=False)

    op.create_table('termeni_urmariti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('entitate_sursa', sa.String(length=30), nullable=False),
    sa.Column('id_entitate_sursa', sa.Integer(), nullable=False),
    sa.Column('tip_regula', sa.String(length=40), nullable=False),
    sa.Column('data_start', sa.Date(), nullable=False),
    sa.Column('data_scadenta', sa.Date(), nullable=False),
    sa.Column('zile_grace', sa.Integer(), nullable=False),
    sa.Column('zile_anticipare', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_indeplinire', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('termeni_urmariti', schema=None) as batch_op:
        batch_op.create_index('ix_termen_urm_status_data', ['status', 'data_scadenta'], unique=False)
        batch_op.create_index('ix_termen_urm_sursa', ['entitate_sursa', 'id_entitate_sursa'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_urmariti_data_scadenta'), ['data_scadenta'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_urmariti_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_urmariti_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_urmariti_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_urmariti_tip_regula'), ['tip_regula'], unique=False)

    op.create_table('corespondente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('numar_inregistrare', sa.String(length=100), nullable=False),
    sa.Column('data_inregistrare', sa.Date(), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('subtip', sa.String(length=50), nullable=True),
    sa.Column('directie', sa.String(length=10), nullable=False),
    sa.Column('expeditor', sa.String(length=255), nullable=True),
    sa.Column('destinatar', sa.String(length=255), nullable=True),
    sa.Column('subiect', sa.String(length=500), nullable=True),
    sa.Column('continut_text', sa.Text(), nullable=True),
    sa.Column('fisier_path', sa.String(length=500), nullable=True),
    sa.Column('genereaza_termen', sa.Boolean(), nullable=False),
    sa.Column('raspuns_la_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['raspuns_la_id'], ['corespondente.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numar_inregistrare', name='uix_coresp_nr_per_tenant')
    )
    with op.batch_alter_table('corespondente', schema=None) as batch_op:
        batch_op.create_index('ix_coresp_proiect_data', ['proiect_id', 'data_inregistrare'], unique=False)
        batch_op.create_index('ix_coresp_subtip_genereaza', ['subtip', 'genereaza_termen'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_directie'), ['directie'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_genereaza_termen'), ['genereaza_termen'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_raspuns_la_id'), ['raspuns_la_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_subtip'), ['subtip'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corespondente_tip'), ['tip'], unique=False)

    op.create_table('oferte_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('versiune', sa.Integer(), nullable=False),
    sa.Column('data_emitere', sa.Date(), nullable=False),
    sa.Column('valoare_totala', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valoare_manopera', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valoare_materiale', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valoare_utilaje', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valoare_transport', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sursa_import', sa.String(length=30), nullable=False),
    sa.Column('fisier_sursa_path', sa.String(length=500), nullable=True),
    sa.Column('aprobata', sa.Boolean(), nullable=False),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'versiune', name='uix_oferta_contract_versiune')
    )
    with op.batch_alter_table('oferte_contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oferte_contract_aprobata'), ['aprobata'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferte_contract_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferte_contract_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferte_contract_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('procese_verbale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('numar', sa.String(length=100), nullable=True),
    sa.Column('data_emitere', sa.Date(), nullable=False),
    sa.Column('participanti_json', sa.Text(), nullable=False),
    sa.Column('obiect', sa.Text(), nullable=True),
    sa.Column('concluzii', sa.Text(), nullable=True),
    sa.Column('template_folosit', sa.String(length=100), nullable=True),
    sa.Column('fisier_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('fisier_docx_path', sa.String(length=500), nullable=True),
    sa.Column('semnat', sa.Boolean(), nullable=False),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procese_verbale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procese_verbale_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procese_verbale_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procese_verbale_semnat'), ['semnat'], unique=False)
        batch_op.create_index(batch_op.f('ix_procese_verbale_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procese_verbale_tip'), ['tip'], unique=False)
        batch_op.create_index('ix_pv_emitere', ['data_emitere'], unique=False)
        batch_op.create_index('ix_pv_proiect_tip', ['proiect_id', 'tip'], unique=False)

    op.create_table('programe_referinta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('versiune', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=255), nullable=False),
    sa.Column('data_emitere', sa.Date(), nullable=False),
    sa.Column('data_inceput_program', sa.Date(), nullable=True),
    sa.Column('data_sfarsit_program', sa.Date(), nullable=True),
    sa.Column('sursa_import', sa.String(length=30), nullable=False),
    sa.Column('fisier_sursa_path', sa.String(length=500), nullable=True),
    sa.Column('aprobat', sa.Boolean(), nullable=False),
    sa.Column('aprobat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_aprobare', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proiect_id', 'versiune', name='uix_program_proiect_versiune')
    )
    with op.batch_alter_table('programe_referinta', schema=None) as batch_op:
        batch_op.create_index('ix_program_proiect_aprobat', ['proiect_id', 'aprobat'], unique=False)
        batch_op.create_index(batch_op.f('ix_programe_referinta_aprobat'), ['aprobat'], unique=False)
        batch_op.create_index(batch_op.f('ix_programe_referinta_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programe_referinta_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programe_referinta_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('situatii_lunare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('luna', sa.Integer(), nullable=False),
    sa.Column('an', sa.Integer(), nullable=False),
    sa.Column('data_emitere', sa.Date(), nullable=False),
    sa.Column('numar_situatie', sa.String(length=50), nullable=True),
    sa.Column('valoare_totala_luna', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valoare_cumulat_la_zi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('procent_avans_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('fisier_export_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('fisier_export_xlsx_path', sa.String(length=500), nullable=True),
    sa.Column('aprobat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_aprobare', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proiect_id', 'an', 'luna', name='uix_situatie_proiect_anluna')
    )
    with op.batch_alter_table('situatii_lunare', schema=None) as batch_op:
        batch_op.create_index('ix_situatie_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_situatii_lunare_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_situatii_lunare_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_situatii_lunare_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_situatii_lunare_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('termeni_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=255), nullable=False),
    sa.Column('tip', sa.String(length=40), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('data_scadenta', sa.Date(), nullable=False),
    sa.Column('data_realizare', sa.Date(), nullable=True),
    sa.Column('zile_alerta_inainte', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsabil_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['responsabil_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('termeni_contract', schema=None) as batch_op:
        batch_op.create_index('ix_termen_proiect_data', ['proiect_id', 'data_scadenta'], unique=False)
        batch_op.create_index('ix_termen_status_data', ['status', 'data_scadenta'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_contract_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_contract_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_contract_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_contract_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termeni_contract_tip'), ['tip'], unique=False)

    op.create_table('revendicari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('numar_revendicare', sa.String(length=100), nullable=False),
    sa.Column('data_emitere', sa.Date(), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('valoare_solicitata', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('zile_prelungire_solicitate', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_decizie', sa.Date(), nullable=True),
    sa.Column('motivare_decizie', sa.Text(), nullable=True),
    sa.Column('corespondenta_initiatoare_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracte.id'], ),
    sa.ForeignKeyConstraint(['corespondenta_initiatoare_id'], ['corespondente.id'], ),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numar_revendicare', name='uix_revend_nr_per_tenant')
    )
    with op.batch_alter_table('revendicari', schema=None) as batch_op:
        batch_op.create_index('ix_revend_emitere', ['data_emitere'], unique=False)
        batch_op.create_index('ix_revend_proiect_status', ['proiect_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_corespondenta_initiatoare_id'), ['corespondenta_initiatoare_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_tip'), ['tip'], unique=False)

    op.create_table('revendicari_termeni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('revendicare_id', sa.Integer(), nullable=False),
    sa.Column('termen_contract_id', sa.Integer(), nullable=False),
    sa.Column('tip_legatura', sa.String(length=20), nullable=False),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revendicare_id'], ['revendicari.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['termen_contract_id'], ['termeni_contract.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revendicare_id', 'termen_contract_id', name='uix_revend_termen')
    )
    with op.batch_alter_table('revendicari_termeni', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revendicari_termeni_revendicare_id'), ['revendicare_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_termeni_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_termeni_termen_contract_id'), ['termen_contract_id'], unique=False)

    op.create_table('pozitii_boq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('parinte_pozitie_id', sa.Integer(), nullable=True),
    sa.Column('cod_articol', sa.String(length=50), nullable=False),
    sa.Column('cod_capitol', sa.String(length=50), nullable=True),
    sa.Column('denumire', sa.Text(), nullable=False),
    sa.Column('um', sa.String(length=20), nullable=False),
    sa.Column('cantitate_oferta', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pret_unitar', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valoare_materiale_unitar', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valoare_manopera_unitar', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valoare_utilaj_unitar', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valoare_transport_unitar', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('categorie', sa.String(length=20), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('bim_cost_item_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bim_cost_item_id'], ['bim_cost_items.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferte_contract.id'], ),
    sa.ForeignKeyConstraint(['parinte_pozitie_id'], ['pozitii_boq.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pozitii_boq', schema=None) as batch_op:
        batch_op.create_index('ix_pozitie_capitol', ['cod_capitol'], unique=False)
        batch_op.create_index('ix_pozitie_oferta_ordine', ['oferta_id', 'ordine'], unique=False)
        batch_op.create_index('ix_pozitie_proiect_cod', ['proiect_id', 'cod_articol'], unique=False)
        batch_op.create_index(batch_op.f('ix_pozitii_boq_bim_cost_item_id'), ['bim_cost_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pozitii_boq_categorie'), ['categorie'], unique=False)
        batch_op.create_index(batch_op.f('ix_pozitii_boq_oferta_id'), ['oferta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pozitii_boq_parinte_pozitie_id'), ['parinte_pozitie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pozitii_boq_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pozitii_boq_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cantitati_executate_lunare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('pozitie_boq_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('luna', sa.Integer(), nullable=False),
    sa.Column('an', sa.Integer(), nullable=False),
    sa.Column('cantitate_executata', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valoare_calculata', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('procent_din_oferta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('inregistrat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_inregistrare', sa.DateTime(), nullable=False),
    sa.Column('validat', sa.Boolean(), nullable=False),
    sa.Column('validat_de_id', sa.Integer(), nullable=True),
    sa.Column('data_validare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inregistrat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['pozitie_boq_id'], ['pozitii_boq.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['validat_de_id'], ['utilizatori.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pozitie_boq_id', 'an', 'luna', name='uix_cantitate_pozitie_lunaan')
    )
    with op.batch_alter_table('cantitati_executate_lunare', schema=None) as batch_op:
        batch_op.create_index('ix_cant_proiect_anluna', ['proiect_id', 'an', 'luna'], unique=False)
        batch_op.create_index(batch_op.f('ix_cantitati_executate_lunare_pozitie_boq_id'), ['pozitie_boq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cantitati_executate_lunare_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cantitati_executate_lunare_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cantitati_executate_lunare_validat'), ['validat'], unique=False)

    op.create_table('taskuri_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('parinte_task_id', sa.Integer(), nullable=True),
    sa.Column('cod_extern', sa.String(length=100), nullable=True),
    sa.Column('cod_wbs', sa.String(length=100), nullable=True),
    sa.Column('denumire', sa.String(length=500), nullable=False),
    sa.Column('nivel_ierarhie', sa.Integer(), nullable=False),
    sa.Column('data_start_planificat', sa.Date(), nullable=False),
    sa.Column('data_sfarsit_planificat', sa.Date(), nullable=False),
    sa.Column('data_start_real', sa.Date(), nullable=True),
    sa.Column('data_sfarsit_real', sa.Date(), nullable=True),
    sa.Column('durata_zile', sa.Integer(), nullable=True),
    sa.Column('procent_realizare', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tip_task', sa.String(length=20), nullable=False),
    sa.Column('predecesori_json', sa.Text(), nullable=False),
    sa.Column('bim_task_schedule_id', sa.Integer(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bim_task_schedule_id'], ['bim_task_schedules.id'], ),
    sa.ForeignKeyConstraint(['parinte_task_id'], ['taskuri_program.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programe_referinta.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'cod_extern', name='uix_task_program_codext')
    )
    with op.batch_alter_table('taskuri_program', schema=None) as batch_op:
        batch_op.create_index('ix_task_program_data', ['program_id', 'data_start_planificat'], unique=False)
        batch_op.create_index('ix_task_proiect_sfarsit', ['proiect_id', 'data_sfarsit_planificat'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskuri_program_bim_task_schedule_id'), ['bim_task_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskuri_program_parinte_task_id'), ['parinte_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskuri_program_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskuri_program_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskuri_program_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskuri_program_tip_task'), ['tip_task'], unique=False)

    op.create_table('revendicari_cantitati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('revendicare_id', sa.Integer(), nullable=False),
    sa.Column('cantitate_lunara_id', sa.Integer(), nullable=False),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cantitate_lunara_id'], ['cantitati_executate_lunare.id'], ),
    sa.ForeignKeyConstraint(['revendicare_id'], ['revendicari.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revendicare_id', 'cantitate_lunara_id', name='uix_revend_cantitate')
    )
    with op.batch_alter_table('revendicari_cantitati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revendicari_cantitati_cantitate_lunara_id'), ['cantitate_lunara_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_cantitati_revendicare_id'), ['revendicare_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_cantitati_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('revendicari_taskuri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('revendicare_id', sa.Integer(), nullable=False),
    sa.Column('task_program_id', sa.Integer(), nullable=False),
    sa.Column('tip_legatura', sa.String(length=20), nullable=False),
    sa.Column('observatii', sa.Text(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revendicare_id'], ['revendicari.id'], ),
    sa.ForeignKeyConstraint(['task_program_id'], ['taskuri_program.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revendicare_id', 'task_program_id', name='uix_revend_task')
    )
    with op.batch_alter_table('revendicari_taskuri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revendicari_taskuri_revendicare_id'), ['revendicare_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_taskuri_task_program_id'), ['task_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revendicari_taskuri_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revendicari_taskuri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revendicari_taskuri_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_taskuri_task_program_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_taskuri_revendicare_id'))

    op.drop_table('revendicari_taskuri')
    with op.batch_alter_table('revendicari_cantitati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revendicari_cantitati_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_cantitati_revendicare_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_cantitati_cantitate_lunara_id'))

    op.drop_table('revendicari_cantitati')
    with op.batch_alter_table('taskuri_program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taskuri_program_tip_task'))
        batch_op.drop_index(batch_op.f('ix_taskuri_program_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_taskuri_program_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_taskuri_program_program_id'))
        batch_op.drop_index(batch_op.f('ix_taskuri_program_parinte_task_id'))
        batch_op.drop_index(batch_op.f('ix_taskuri_program_bim_task_schedule_id'))
        batch_op.drop_index('ix_task_proiect_sfarsit')
        batch_op.drop_index('ix_task_program_data')

    op.drop_table('taskuri_program')
    with op.batch_alter_table('cantitati_executate_lunare', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cantitati_executate_lunare_validat'))
        batch_op.drop_index(batch_op.f('ix_cantitati_executate_lunare_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cantitati_executate_lunare_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_cantitati_executate_lunare_pozitie_boq_id'))
        batch_op.drop_index('ix_cant_proiect_anluna')

    op.drop_table('cantitati_executate_lunare')
    with op.batch_alter_table('pozitii_boq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_parinte_pozitie_id'))
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_oferta_id'))
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_categorie'))
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_bim_cost_item_id'))
        batch_op.drop_index('ix_pozitie_proiect_cod')
        batch_op.drop_index('ix_pozitie_oferta_ordine')
        batch_op.drop_index('ix_pozitie_capitol')

    op.drop_table('pozitii_boq')
    with op.batch_alter_table('revendicari_termeni', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revendicari_termeni_termen_contract_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_termeni_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_termeni_revendicare_id'))

    op.drop_table('revendicari_termeni')
    with op.batch_alter_table('revendicari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revendicari_tip'))
        batch_op.drop_index(batch_op.f('ix_revendicari_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_status'))
        batch_op.drop_index(batch_op.f('ix_revendicari_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_corespondenta_initiatoare_id'))
        batch_op.drop_index(batch_op.f('ix_revendicari_contract_id'))
        batch_op.drop_index('ix_revend_proiect_status')
        batch_op.drop_index('ix_revend_emitere')

    op.drop_table('revendicari')
    with op.batch_alter_table('termeni_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termeni_contract_tip'))
        batch_op.drop_index(batch_op.f('ix_termeni_contract_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_termeni_contract_status'))
        batch_op.drop_index(batch_op.f('ix_termeni_contract_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_termeni_contract_contract_id'))
        batch_op.drop_index('ix_termen_status_data')
        batch_op.drop_index('ix_termen_proiect_data')

    op.drop_table('termeni_contract')
    with op.batch_alter_table('situatii_lunare', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_situatii_lunare_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_situatii_lunare_status'))
        batch_op.drop_index(batch_op.f('ix_situatii_lunare_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_situatii_lunare_contract_id'))
        batch_op.drop_index('ix_situatie_status')

    op.drop_table('situatii_lunare')
    with op.batch_alter_table('programe_referinta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programe_referinta_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_programe_referinta_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_programe_referinta_contract_id'))
        batch_op.drop_index(batch_op.f('ix_programe_referinta_aprobat'))
        batch_op.drop_index('ix_program_proiect_aprobat')

    op.drop_table('programe_referinta')
    with op.batch_alter_table('procese_verbale', schema=None) as batch_op:
        batch_op.drop_index('ix_pv_proiect_tip')
        batch_op.drop_index('ix_pv_emitere')
        batch_op.drop_index(batch_op.f('ix_procese_verbale_tip'))
        batch_op.drop_index(batch_op.f('ix_procese_verbale_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_procese_verbale_semnat'))
        batch_op.drop_index(batch_op.f('ix_procese_verbale_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_procese_verbale_contract_id'))

    op.drop_table('procese_verbale')
    with op.batch_alter_table('oferte_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oferte_contract_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_oferte_contract_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_oferte_contract_contract_id'))
        batch_op.drop_index(batch_op.f('ix_oferte_contract_aprobata'))

    op.drop_table('oferte_contract')
    with op.batch_alter_table('corespondente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corespondente_tip'))
        batch_op.drop_index(batch_op.f('ix_corespondente_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_corespondente_subtip'))
        batch_op.drop_index(batch_op.f('ix_corespondente_raspuns_la_id'))
        batch_op.drop_index(batch_op.f('ix_corespondente_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_corespondente_genereaza_termen'))
        batch_op.drop_index(batch_op.f('ix_corespondente_directie'))
        batch_op.drop_index(batch_op.f('ix_corespondente_contract_id'))
        batch_op.drop_index('ix_coresp_subtip_genereaza')
        batch_op.drop_index('ix_coresp_proiect_data')

    op.drop_table('corespondente')
    with op.batch_alter_table('termeni_urmariti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termeni_urmariti_tip_regula'))
        batch_op.drop_index(batch_op.f('ix_termeni_urmariti_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_termeni_urmariti_status'))
        batch_op.drop_index(batch_op.f('ix_termeni_urmariti_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_termeni_urmariti_data_scadenta'))
        batch_op.drop_index('ix_termen_urm_sursa')
        batch_op.drop_index('ix_termen_urm_status_data')

    op.drop_table('termeni_urmariti')
    with op.batch_alter_table('reguli_notificare_proiect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reguli_notificare_proiect_tip_eveniment'))
        batch_op.drop_index(batch_op.f('ix_reguli_notificare_proiect_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reguli_notificare_proiect_proiect_id'))

    op.drop_table('reguli_notificare_proiect')
    with op.batch_alter_table('rapoarte_lucrari_proiect', schema=None) as batch_op:
        batch_op.drop_index('ix_raport_lucr_proiect_anluna')
        batch_op.drop_index(batch_op.f('ix_rapoarte_lucrari_proiect_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_rapoarte_lucrari_proiect_proiect_id'))

    op.drop_table('rapoarte_lucrari_proiect')
    with op.batch_alter_table('contracte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracte_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_contracte_status'))
        batch_op.drop_index(batch_op.f('ix_contracte_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_contracte_parinte_contract_id'))
        batch_op.drop_index('ix_contract_proiect_status')
        batch_op.drop_index('ix_contract_finalizare')

    op.drop_table('contracte')
    with op.batch_alter_table('notificari_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificari_app_utilizator_id'))
        batch_op.drop_index(batch_op.f('ix_notificari_app_tip'))
        batch_op.drop_index(batch_op.f('ix_notificari_app_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notificari_app_citita'))
        batch_op.drop_index('ix_notif_user_citita_data')

    op.drop_table('notificari_app')
    with op.batch_alter_table('anexe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexe_tip_fisier'))
        batch_op.drop_index(batch_op.f('ix_anexe_tenant_id'))
        batch_op.drop_index('ix_anexa_tinta')

    op.drop_table('anexe')
    # ### end Alembic commands ###
