"""0010 locatii proiect

Revision ID: 0010_locatii_proiect
Revises: 0009_contract_controls
Create Date: 2026-05-19 08:50:28.040685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010_locatii_proiect'
down_revision: Union[str, Sequence[str], None] = '0009_contract_controls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locatii_proiect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=200), nullable=False),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitudine', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitudine', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('adresa_text', sa.String(length=500), nullable=True),
    sa.Column('adresa_normalizata', sa.String(length=500), nullable=True),
    sa.Column('judet', sa.String(length=100), nullable=True),
    sa.Column('localitate', sa.String(length=200), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locatii_proiect', schema=None) as batch_op:
        batch_op.create_index('ix_locatie_coord', ['latitudine', 'longitudine'], unique=False)
        batch_op.create_index('ix_locatie_proiect_status', ['proiect_id', 'status'], unique=False)
        batch_op.create_index('ix_locatie_proiect_tip', ['proiect_id', 'tip'], unique=False)
        batch_op.create_index(batch_op.f('ix_locatii_proiect_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locatii_proiect_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_locatii_proiect_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locatii_proiect_tip'), ['tip'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locatii_proiect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locatii_proiect_tip'))
        batch_op.drop_index(batch_op.f('ix_locatii_proiect_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_locatii_proiect_status'))
        batch_op.drop_index(batch_op.f('ix_locatii_proiect_proiect_id'))
        batch_op.drop_index('ix_locatie_proiect_tip')
        batch_op.drop_index('ix_locatie_proiect_status')
        batch_op.drop_index('ix_locatie_coord')

    op.drop_table('locatii_proiect')
    # ### end Alembic commands ###
