"""0011 deviz pricing

Revision ID: 0011_deviz_pricing
Revises: 0010_locatii_proiect
Create Date: 2026-05-22 12:26:39.336774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011_deviz_pricing'
down_revision: Union[str, Sequence[str], None] = '0010_locatii_proiect'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarife_categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('proiect_id', sa.Integer(), nullable=True),
    sa.Column('disciplina', sa.String(length=40), nullable=False),
    sa.Column('categorie_lucrare', sa.String(length=60), nullable=False),
    sa.Column('tarif_baza', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('um_referinta', sa.String(length=20), nullable=True),
    sa.Column('data_creare', sa.DateTime(), nullable=False),
    sa.Column('creat_de_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creat_de_id'], ['utilizatori.id'], ),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proiect_id', 'disciplina', 'categorie_lucrare', name='uix_tarif_proiect_disc_cat')
    )
    with op.batch_alter_table('tarife_categorie', schema=None) as batch_op:
        batch_op.create_index('ix_tarif_disc_cat', ['disciplina', 'categorie_lucrare'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarife_categorie_disciplina'), ['disciplina'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarife_categorie_proiect_id'), ['proiect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarife_categorie_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('pozitii_boq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie_lucrare', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('factor_aleator', sa.Numeric(precision=6, scale=4), nullable=True))
        batch_op.create_index(batch_op.f('ix_pozitii_boq_categorie_lucrare'), ['categorie_lucrare'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pozitii_boq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pozitii_boq_categorie_lucrare'))
        batch_op.drop_column('factor_aleator')
        batch_op.drop_column('categorie_lucrare')

    with op.batch_alter_table('tarife_categorie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarife_categorie_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tarife_categorie_proiect_id'))
        batch_op.drop_index(batch_op.f('ix_tarife_categorie_disciplina'))
        batch_op.drop_index('ix_tarif_disc_cat')

    op.drop_table('tarife_categorie')
    # ### end Alembic commands ###
